### ISSUE TITLE
Return json instead of array

### ISSUE THREAD

**Issue by ChristopherDosin** [huddledigital/zendesk-laravel#2]
Thanks for the package,

would you tell me how i can return the results as json instead of an array?

**Comment by harry-huddle** [comment]
Hi Kay,

Since our package is just a wrapper for the Zendesk API client, it's the response from that which gives you it as an array. I've found the file and line where the json is decoded, you would have to override this file and method in order to get a json result.

Line 108 of this file: https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Http.php

To be honest though, it's probably more effort than it's worth, if you need json it would be easier to just json_encode it I think.

Harry
